version: 2

jobs:
  build:
    docker:
      - image: aabadie/cayenne-lpp
    steps:
      - checkout
      - run:
          command: make
      - run:
          command: example/example
      - run:
          command: make check
      - run:
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          command: make doc
      - store_artifacts:
          path: doc/html
          destination: doc
